hazelcast:
    config:
        group:
            name: group-dev
            password: group-dev
        network:
            port: 8705
            port-auto-increment: true
            multicast:
                enabled: false
            tcp-ip:
                enabled: true
            aws:
                enabled: false

aws:
   accessKey: ${awsKey:none}
   secretKey: ${awsPwd:none}
   region: us-west-1

lists:
    aList:
        - "First"
        - "Second"
