hazelcast:
    config:
        group:
            name: group-dev
            password: group-dev
        network:
            port: 8705
            port-auto-increment: true
            multicast:
                enabled: false
            tcp-ip:
                enabled: true
                members: instance1:8705, instance2:8705
            aws:
                enabled: false
            docker:
                enabled: false
                networkNames: caching_vpc
                serviceNames: instance1,instance2
                serviceLabels:
