hazelcast:
    config:
        group:
            name: group-dev
            password: group-dev
        network:
            port: 7745
            port-auto-increment: false
            multicast:
                enabled: true
            tcp-ip:
                enabled: false
            aws:
                enabled: false
                security-group-name: sg-hazelcast

aws:
   accessKey: ${awsKey:none}
   secretKey: ${awsPwd:none}
   region: us-west-1