FROM openjdk:8u131-jre-alpine

VOLUME /tmp
ADD ${jar_name}-${jar_version}.jar /home/${jar_name}.jar
RUN apk --update add curl

EXPOSE 7745

ENTRYPOINT ["sh","-c","java \$JAVA_OPTS -jar /home/${jar_name}.jar"]
